pipelines:
 default:
  - step:
      name: Sync GitHub Mirror
      image: alpine/git:latest
      clone:
        enabled: false
      script:
        - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/succpinnsolutions/ecommerce_app.git ## @bitbucket.org follow by your Bitbucket repository path
        - cd ecommerce_app.git ## cd followed by your Github repository Name
        - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/felix-momodebe-official/bitbucket-sync.git ## @github.com followed by your Github repository path